title: Teklay Gebremichael Welegebrael
logo: /home/tek/Picures/cropped_portrait.jpg
#description: text below image
show_downloads: true
theme: jekyll-theme-minimal
#other jeykyll themes, visit https://pages.github.com/themes/

