title: Teklay Gebremichael Welegebrael
logo: cropped_portrait.jpg
#description: text below image
show_downloads: true
theme: jekyll-theme-midnight
#other jeykyll themes, visit https://pages.github.com/themes/

