title: Teklay Gebremichael Welegebrael
#logo: https://github.com/teklayge/teklayge.github.io/blob/main/cropped_portrait.jpg
logo: image/cropped_portrait.jpg
description: Dependable data analyst practioner
show_downloads: true
theme: jekyll-theme-modernist
#other jeykyll themes, visit https://pages.github.com/themes/

